name: Build and Push Image for Folder2

on:
  push:
    paths:
      - 'folder2/**'
      - 'folder2/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Git tag
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Extract short commit hash
        id: get_commit
        run: echo "commit_hash=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set image name
        run: echo "IMAGE_NAME=myimage2" >> $GITHUB_ENV

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image for folder2
        run: |
          TAG=${{ env.tag || env.commit_hash }}
          IMAGE=ghcr.io/${{ github.repository }}/$IMAGE_NAME:$TAG
          cd folder2
          docker build -t $IMAGE .
          docker push $IMAGE



--


name: Build Image2

on:
  push:
    paths:
      - 'folder2/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: myimage2
      DOCKER_REGISTRY: ghcr.io

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest ./folder2
        docker tag ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Login to GitHub Docker Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
