name: Build and Push Image for Folder2

on:
  push:
    branches:
    - first-docker-image
    paths:
      - devcontainers/go-grpc/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Git tag
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Extract short commit hash
        id: get_commit
        run: echo "commit_hash=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set image name
        run: echo "IMAGE_NAME=dev-go-npm-grpc-java-android" >> $GITHUB_ENV

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image for folder2
        run: |
          TAG=${{ env.tag || env.commit_hash }}
          IMAGE=ghcr.io/${{ github.repository }}/$IMAGE_NAME:$TAG
          cd devcontainers/go-grpc
          docker build -t $IMAGE .
          docker push $IMAGE

